INFO 2025-04-08 20:56:05,714 autoreload 19068 23908 Watching for file changes with StatReloader
ERROR 2025-04-08 20:56:09,911 log 19068 21016 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: dashboard_destination

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\dashboard\views.py", line 41, in get_context_data
    destination_count = Destination.objects.count()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\sentry_sdk\integrations\django\__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryank\PycharmProjects\airbnb_analytics\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: dashboard_destination
ERROR 2025-04-08 20:56:09,928 basehttp 19068 21016 "GET / HTTP/1.1" 500 161944
WARNING 2025-04-08 20:56:11,025 log 19068 21016 Not Found: /favicon.ico
WARNING 2025-04-08 20:56:11,033 basehttp 19068 21016 "GET /favicon.ico HTTP/1.1" 404 3547
INFO 2025-04-08 20:59:27,216 autoreload 24880 23712 Watching for file changes with StatReloader
INFO 2025-04-08 20:59:44,257 basehttp 24880 19912 "GET / HTTP/1.1" 200 15043
INFO 2025-04-08 20:59:58,277 basehttp 24880 19844 "GET /dashboard/ HTTP/1.1" 200 20906
INFO 2025-04-08 21:00:08,004 basehttp 24880 19372 "GET /destinations/add/ HTTP/1.1" 302 0
WARNING 2025-04-08 21:00:08,032 log 24880 19372 Not Found: /accounts/login/
WARNING 2025-04-08 21:00:08,039 basehttp 24880 19372 "GET /accounts/login/?next=/destinations/add/ HTTP/1.1" 404 3583
INFO 2025-04-08 21:00:23,108 basehttp 24880 23360 "GET / HTTP/1.1" 200 15043
INFO 2025-04-08 21:00:25,168 basehttp 24880 23360 "GET /destinations/add/ HTTP/1.1" 302 0
WARNING 2025-04-08 21:00:25,185 log 24880 23360 Not Found: /accounts/login/
WARNING 2025-04-08 21:00:25,193 basehttp 24880 23360 "GET /accounts/login/?next=/destinations/add/ HTTP/1.1" 404 3583
